
/* Autogenerated file, do not edit! */

/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractMethod, type ContractStorageLayout, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
import FogOfWarChessContractArtifactJson from '../target/fog_of_war_chess-FogOfWarChess.json' with { type: 'json' };
export const FogOfWarChessContractArtifact = loadContractArtifact(FogOfWarChessContractArtifactJson as NoirCompiledContract);


      export type NewGame = {
        game_id: (bigint | number)
password_hash: FieldLike
initial_state: FieldLike[]
      }
    

      export type MoveEvent = {
        state: { ciphertext: { data: FieldLike[] }, mask_commitments: { x: FieldLike, y: FieldLike, is_infinite: boolean }[], user_updated_mask_commitments: { x: FieldLike, y: FieldLike, is_infinite: boolean }[][] }
      }
    

      export type JoinedGame = {
        game_id: (bigint | number)
password_hash: FieldLike
initial_state: FieldLike[]
      }
    

/**
 * Type-safe interface for contract FogOfWarChess;
 */
export class FogOfWarChessContract extends ContractBase {
  
  private constructor(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    super(address, FogOfWarChessContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(
    address: AztecAddress,
    wallet: Wallet,
  ): FogOfWarChessContract {
    return Contract.at(address, FogOfWarChessContract.artifact, wallet) as FogOfWarChessContract;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, ) {
    return new DeployMethod<FogOfWarChessContract>(PublicKeys.default(), wallet, FogOfWarChessContractArtifact, (instance, wallet) => FogOfWarChessContract.at(instance.address, wallet), Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, ) {
    return new DeployMethod<FogOfWarChessContract>(publicKeys, wallet, FogOfWarChessContractArtifact, (instance, wallet) => FogOfWarChessContract.at(instance.address, wallet), Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof FogOfWarChessContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<FogOfWarChessContract['methods'][M]>
  ) {
    return new DeployMethod<FogOfWarChessContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      FogOfWarChessContractArtifact,
      (instance, wallet) => FogOfWarChessContract.at(instance.address, wallet),
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return FogOfWarChessContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(FogOfWarChessContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'game_counter' | 'game_secret_hashes' | 'game_hashes' | 'elo_ratings' | 'game_players' | 'hat_nft_address'> {
      return {
        game_counter: {
      slot: new Fr(1n),
    },
game_secret_hashes: {
      slot: new Fr(2n),
    },
game_hashes: {
      slot: new Fr(3n),
    },
elo_ratings: {
      slot: new Fr(4n),
    },
game_players: {
      slot: new Fr(5n),
    },
hat_nft_address: {
      slot: new Fr(6n),
    }
      } as ContractStorageLayout<'game_counter' | 'game_secret_hashes' | 'game_hashes' | 'elo_ratings' | 'game_players' | 'hat_nft_address'>;
    }
    

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** __commit_to_user_secrets(game_state: struct, encrypt_secret: field, mask_secret: field, player_id: field) */
    __commit_to_user_secrets: ((game_state: { game_ended: boolean, move_count: FieldLike, mpc_state: { round_number: (bigint | number), user_encrypt_secret_hashes: FieldLike[], user_mask_secret_hashes: FieldLike[], previous_output_states: { ciphertext: { data: FieldLike[] }, mask_commitments: { x: FieldLike, y: FieldLike, is_infinite: boolean }[], user_updated_mask_commitments: { x: FieldLike, y: FieldLike, is_infinite: boolean }[][] }[] } }, encrypt_secret: FieldLike, mask_secret: FieldLike, player_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** __consume_opponent_move(input_state: struct, user_state: struct, player_id: field) */
    __consume_opponent_move: ((input_state: { game_ended: boolean, move_count: FieldLike, mpc_state: { round_number: (bigint | number), user_encrypt_secret_hashes: FieldLike[], user_mask_secret_hashes: FieldLike[], previous_output_states: { ciphertext: { data: FieldLike[] }, mask_commitments: { x: FieldLike, y: FieldLike, is_infinite: boolean }[], user_updated_mask_commitments: { x: FieldLike, y: FieldLike, is_infinite: boolean }[][] }[] } }, user_state: { encrypt_secret: FieldLike, mask_secret: FieldLike, visible_squares: FieldLike[], game_state: { id: FieldLike, player_id: FieldLike, has_moved: FieldLike }[] }, player_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** __create_move(x1: field, y1: field, x2: field, y2: field) */
    __create_move: ((x1: FieldLike, y1: FieldLike, x2: FieldLike, y2: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** __empty_black_state() */
    __empty_black_state: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** __empty_game_state() */
    __empty_game_state: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** __empty_white_state() */
    __empty_white_state: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** __get_elo_rating(player: struct) */
    __get_elo_rating: ((player: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** __get_game_players(game_id: integer) */
    __get_game_players: ((game_id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** __get_game_secret_hashes(game_id: integer) */
    __get_game_secret_hashes: ((game_id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** __get_hat_nft_address() */
    __get_hat_nft_address: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** __update_game_state_from_move(input_state: struct, user_state: struct, player_id: field) */
    __update_game_state_from_move: ((input_state: { game_ended: boolean, move_count: FieldLike, mpc_state: { round_number: (bigint | number), user_encrypt_secret_hashes: FieldLike[], user_mask_secret_hashes: FieldLike[], previous_output_states: { ciphertext: { data: FieldLike[] }, mask_commitments: { x: FieldLike, y: FieldLike, is_infinite: boolean }[], user_updated_mask_commitments: { x: FieldLike, y: FieldLike, is_infinite: boolean }[][] }[] } }, user_state: { ciphertext: { data: FieldLike[] }, mask_commitments: { x: FieldLike, y: FieldLike, is_infinite: boolean }[], user_updated_mask_commitments: { x: FieldLike, y: FieldLike, is_infinite: boolean }[][] }, player_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** __update_user_state_from_move(is_first_two_moves: boolean, _user_state: struct, move_data: struct, player_id: field) */
    __update_user_state_from_move: ((is_first_two_moves: boolean, _user_state: { encrypt_secret: FieldLike, mask_secret: FieldLike, visible_squares: FieldLike[], game_state: { id: FieldLike, player_id: FieldLike, has_moved: FieldLike }[] }, move_data: { x1: FieldLike, y1: FieldLike, x2: FieldLike, y2: FieldLike }, player_id: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** create_game_private(user_secret: field, user_mask: field, password: field) */
    create_game_private: ((user_secret: FieldLike, user_mask: FieldLike, password: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** join_game_private(game_id: integer, user_secret: field, user_mask: field, black_secret_hashes: array, password: field) */
    join_game_private: ((game_id: (bigint | number), user_secret: FieldLike, user_mask: FieldLike, black_secret_hashes: FieldLike[], password: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** make_move_black_private(game_id: integer, game_state: struct, user_state: struct, move_data: struct) */
    make_move_black_private: ((game_id: (bigint | number), game_state: { game_ended: boolean, move_count: FieldLike, mpc_state: { round_number: (bigint | number), user_encrypt_secret_hashes: FieldLike[], user_mask_secret_hashes: FieldLike[], previous_output_states: { ciphertext: { data: FieldLike[] }, mask_commitments: { x: FieldLike, y: FieldLike, is_infinite: boolean }[], user_updated_mask_commitments: { x: FieldLike, y: FieldLike, is_infinite: boolean }[][] }[] } }, user_state: { encrypt_secret: FieldLike, mask_secret: FieldLike, visible_squares: FieldLike[], game_state: { id: FieldLike, player_id: FieldLike, has_moved: FieldLike }[] }, move_data: { x1: FieldLike, y1: FieldLike, x2: FieldLike, y2: FieldLike }) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** make_move_white_private(game_id: integer, game_state: struct, user_state: struct, move_data: struct) */
    make_move_white_private: ((game_id: (bigint | number), game_state: { game_ended: boolean, move_count: FieldLike, mpc_state: { round_number: (bigint | number), user_encrypt_secret_hashes: FieldLike[], user_mask_secret_hashes: FieldLike[], previous_output_states: { ciphertext: { data: FieldLike[] }, mask_commitments: { x: FieldLike, y: FieldLike, is_infinite: boolean }[], user_updated_mask_commitments: { x: FieldLike, y: FieldLike, is_infinite: boolean }[][] }[] } }, user_state: { encrypt_secret: FieldLike, mask_secret: FieldLike, visible_squares: FieldLike[], game_state: { id: FieldLike, player_id: FieldLike, has_moved: FieldLike }[] }, move_data: { x1: FieldLike, y1: FieldLike, x2: FieldLike, y2: FieldLike }) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** process_message(message_ciphertext: struct, message_context: struct) */
    process_message: ((message_ciphertext: FieldLike[], message_context: { tx_hash: FieldLike, unique_note_hashes_in_tx: FieldLike[], first_nullifier_in_tx: FieldLike, recipient: AztecAddressLike }) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** set_hat_nft_address(nft_address: struct) */
    set_hat_nft_address: ((nft_address: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** setup() */
    setup: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_state() */
    sync_state: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
    public static get events(): { NewGame: {abiType: AbiType, eventSelector: EventSelector, fieldNames: string[] }, MoveEvent: {abiType: AbiType, eventSelector: EventSelector, fieldNames: string[] }, JoinedGame: {abiType: AbiType, eventSelector: EventSelector, fieldNames: string[] } } {
    return {
      NewGame: {
        abiType: {
    "kind": "struct",
    "fields": [
        {
            "name": "game_id",
            "type": {
                "kind": "integer",
                "sign": "unsigned",
                "width": 32
            }
        },
        {
            "name": "password_hash",
            "type": {
                "kind": "field"
            }
        },
        {
            "name": "initial_state",
            "type": {
                "kind": "array",
                "length": 2,
                "type": {
                    "kind": "field"
                }
            }
        }
    ],
    "path": "FogOfWarChess::NewGame"
},
        eventSelector: EventSelector.fromString("0xf7ac39c9"),
        fieldNames: ["game_id","password_hash","initial_state"],
      },
MoveEvent: {
        abiType: {
    "kind": "struct",
    "fields": [
        {
            "name": "state",
            "type": {
                "kind": "struct",
                "fields": [
                    {
                        "name": "ciphertext",
                        "type": {
                            "kind": "struct",
                            "fields": [
                                {
                                    "name": "data",
                                    "type": {
                                        "kind": "array",
                                        "length": 128,
                                        "type": {
                                            "kind": "field"
                                        }
                                    }
                                }
                            ],
                            "path": "mpclib::common::crypto::Ciphertext"
                        }
                    },
                    {
                        "name": "mask_commitments",
                        "type": {
                            "kind": "array",
                            "length": 64,
                            "type": {
                                "kind": "struct",
                                "fields": [
                                    {
                                        "name": "x",
                                        "type": {
                                            "kind": "field"
                                        }
                                    },
                                    {
                                        "name": "y",
                                        "type": {
                                            "kind": "field"
                                        }
                                    },
                                    {
                                        "name": "is_infinite",
                                        "type": {
                                            "kind": "boolean"
                                        }
                                    }
                                ],
                                "path": "std::embedded_curve_ops::EmbeddedCurvePoint"
                            }
                        }
                    },
                    {
                        "name": "user_updated_mask_commitments",
                        "type": {
                            "kind": "array",
                            "length": 1,
                            "type": {
                                "kind": "array",
                                "length": 64,
                                "type": {
                                    "kind": "struct",
                                    "fields": [
                                        {
                                            "name": "x",
                                            "type": {
                                                "kind": "field"
                                            }
                                        },
                                        {
                                            "name": "y",
                                            "type": {
                                                "kind": "field"
                                            }
                                        },
                                        {
                                            "name": "is_infinite",
                                            "type": {
                                                "kind": "boolean"
                                            }
                                        }
                                    ],
                                    "path": "std::embedded_curve_ops::EmbeddedCurvePoint"
                                }
                            }
                        }
                    }
                ],
                "path": "mpclib::selective_disclosure::selective_disclosure::UserOutputState"
            }
        }
    ],
    "path": "FogOfWarChess::MoveEvent"
},
        eventSelector: EventSelector.fromString("0xe983606e"),
        fieldNames: ["state"],
      },
JoinedGame: {
        abiType: {
    "kind": "struct",
    "fields": [
        {
            "name": "game_id",
            "type": {
                "kind": "integer",
                "sign": "unsigned",
                "width": 32
            }
        },
        {
            "name": "password_hash",
            "type": {
                "kind": "field"
            }
        },
        {
            "name": "initial_state",
            "type": {
                "kind": "array",
                "length": 2,
                "type": {
                    "kind": "field"
                }
            }
        }
    ],
    "path": "FogOfWarChess::JoinedGame"
},
        eventSelector: EventSelector.fromString("0x49999138"),
        fieldNames: ["game_id","password_hash","initial_state"],
      }
    };
  }
  
}
