
/* Autogenerated file, do not edit! */

/* eslint-disable */
import { AztecAddress, CompleteAddress } from '@aztec/aztec.js/addresses';
import { type AbiType, type AztecAddressLike, type ContractArtifact, EventSelector, decodeFromAbi, type EthAddressLike, type FieldLike, type FunctionSelectorLike, loadContractArtifact, loadContractArtifactForPublic, type NoirCompiledContract, type U128Like, type WrappedFieldLike } from '@aztec/aztec.js/abi';
import { Contract, ContractBase, ContractFunctionInteraction, type ContractMethod, type ContractStorageLayout, DeployMethod } from '@aztec/aztec.js/contracts';
import { EthAddress } from '@aztec/aztec.js/addresses';
import { Fr, Point } from '@aztec/aztec.js/fields';
import { type PublicKey, PublicKeys } from '@aztec/aztec.js/keys';
import type { Wallet } from '@aztec/aztec.js/wallet';
import HatNFTContractArtifactJson from '../target/hat_nft-HatNFT.json' with { type: 'json' };
export const HatNFTContractArtifact = loadContractArtifact(HatNFTContractArtifactJson as NoirCompiledContract);


      export type HatTransferred = {
        token_id: (bigint | number)
from: AztecAddressLike
to: AztecAddressLike
      }
    

      export type HatMinted = {
        token_id: (bigint | number)
owner: AztecAddressLike
game_id: (bigint | number)
hat_type: (bigint | number)
hat_quality: (bigint | number)
      }
    

/**
 * Type-safe interface for contract HatNFT;
 */
export class HatNFTContract extends ContractBase {
  
  private constructor(
    address: AztecAddress,
    wallet: Wallet,
  ) {
    super(address, HatNFTContractArtifact, wallet);
  }
  

  
  /**
   * Creates a contract instance.
   * @param address - The deployed contract's address.
   * @param wallet - The wallet to use when interacting with the contract.
   * @returns A new Contract instance.
   */
  public static at(
    address: AztecAddress,
    wallet: Wallet,
  ): HatNFTContract {
    return Contract.at(address, HatNFTContract.artifact, wallet) as HatNFTContract;
  }

  
  /**
   * Creates a tx to deploy a new instance of this contract.
   */
  public static deploy(wallet: Wallet, chess_contract: AztecAddressLike) {
    return new DeployMethod<HatNFTContract>(PublicKeys.default(), wallet, HatNFTContractArtifact, (instance, wallet) => HatNFTContract.at(instance.address, wallet), Array.from(arguments).slice(1));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified public keys hash to derive the address.
   */
  public static deployWithPublicKeys(publicKeys: PublicKeys, wallet: Wallet, chess_contract: AztecAddressLike) {
    return new DeployMethod<HatNFTContract>(publicKeys, wallet, HatNFTContractArtifact, (instance, wallet) => HatNFTContract.at(instance.address, wallet), Array.from(arguments).slice(2));
  }

  /**
   * Creates a tx to deploy a new instance of this contract using the specified constructor method.
   */
  public static deployWithOpts<M extends keyof HatNFTContract['methods']>(
    opts: { publicKeys?: PublicKeys; method?: M; wallet: Wallet },
    ...args: Parameters<HatNFTContract['methods'][M]>
  ) {
    return new DeployMethod<HatNFTContract>(
      opts.publicKeys ?? PublicKeys.default(),
      opts.wallet,
      HatNFTContractArtifact,
      (instance, wallet) => HatNFTContract.at(instance.address, wallet),
      Array.from(arguments).slice(1),
      opts.method ?? 'constructor',
    );
  }
  

  
  /**
   * Returns this contract's artifact.
   */
  public static get artifact(): ContractArtifact {
    return HatNFTContractArtifact;
  }

  /**
   * Returns this contract's artifact with public bytecode.
   */
  public static get artifactForPublic(): ContractArtifact {
    return loadContractArtifactForPublic(HatNFTContractArtifactJson as NoirCompiledContract);
  }
  

  public static get storage(): ContractStorageLayout<'token_counter' | 'public_owners' | 'nft_exists' | 'hat_game_ids' | 'hat_types' | 'hat_qualities' | 'minter'> {
      return {
        token_counter: {
      slot: new Fr(1n),
    },
public_owners: {
      slot: new Fr(2n),
    },
nft_exists: {
      slot: new Fr(3n),
    },
hat_game_ids: {
      slot: new Fr(4n),
    },
hat_types: {
      slot: new Fr(5n),
    },
hat_qualities: {
      slot: new Fr(6n),
    },
minter: {
      slot: new Fr(7n),
    }
      } as ContractStorageLayout<'token_counter' | 'public_owners' | 'nft_exists' | 'hat_game_ids' | 'hat_types' | 'hat_qualities' | 'minter'>;
    }
    

  /** Type-safe wrappers for the public methods exposed by the contract. */
  public declare methods: {
    
    /** constructor(chess_contract: struct) */
    constructor: ((chess_contract: AztecAddressLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** exists(token_id: integer) */
    exists: ((token_id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_hat_metadata(token_id: integer) */
    get_hat_metadata: ((token_id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** get_minter() */
    get_minter: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** mint_hat(to: struct, game_id: integer, winner_elo: integer, loser_elo: integer) */
    mint_hat: ((to: AztecAddressLike, game_id: (bigint | number), winner_elo: (bigint | number), loser_elo: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** owner_of(token_id: integer) */
    owner_of: ((token_id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** process_message(message_ciphertext: struct, message_context: struct) */
    process_message: ((message_ciphertext: FieldLike[], message_context: { tx_hash: FieldLike, unique_note_hashes_in_tx: FieldLike[], first_nullifier_in_tx: FieldLike, recipient: AztecAddressLike }) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** public_dispatch(selector: field) */
    public_dispatch: ((selector: FieldLike) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** sync_state() */
    sync_state: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** total_supply() */
    total_supply: (() => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;

    /** transfer(from: struct, to: struct, token_id: integer) */
    transfer: ((from: AztecAddressLike, to: AztecAddressLike, token_id: (bigint | number)) => ContractFunctionInteraction) & Pick<ContractMethod, 'selector'>;
  };

  
    public static get events(): { HatTransferred: {abiType: AbiType, eventSelector: EventSelector, fieldNames: string[] }, HatMinted: {abiType: AbiType, eventSelector: EventSelector, fieldNames: string[] } } {
    return {
      HatTransferred: {
        abiType: {
    "kind": "struct",
    "fields": [
        {
            "name": "token_id",
            "type": {
                "kind": "integer",
                "sign": "unsigned",
                "width": 32
            }
        },
        {
            "name": "from",
            "type": {
                "kind": "struct",
                "fields": [
                    {
                        "name": "inner",
                        "type": {
                            "kind": "field"
                        }
                    }
                ],
                "path": "protocol_types::address::aztec_address::AztecAddress"
            }
        },
        {
            "name": "to",
            "type": {
                "kind": "struct",
                "fields": [
                    {
                        "name": "inner",
                        "type": {
                            "kind": "field"
                        }
                    }
                ],
                "path": "protocol_types::address::aztec_address::AztecAddress"
            }
        }
    ],
    "path": "HatNFT::HatTransferred"
},
        eventSelector: EventSelector.fromString("0xc4da60e9"),
        fieldNames: ["token_id","from","to"],
      },
HatMinted: {
        abiType: {
    "kind": "struct",
    "fields": [
        {
            "name": "token_id",
            "type": {
                "kind": "integer",
                "sign": "unsigned",
                "width": 32
            }
        },
        {
            "name": "owner",
            "type": {
                "kind": "struct",
                "fields": [
                    {
                        "name": "inner",
                        "type": {
                            "kind": "field"
                        }
                    }
                ],
                "path": "protocol_types::address::aztec_address::AztecAddress"
            }
        },
        {
            "name": "game_id",
            "type": {
                "kind": "integer",
                "sign": "unsigned",
                "width": 32
            }
        },
        {
            "name": "hat_type",
            "type": {
                "kind": "integer",
                "sign": "unsigned",
                "width": 8
            }
        },
        {
            "name": "hat_quality",
            "type": {
                "kind": "integer",
                "sign": "unsigned",
                "width": 8
            }
        }
    ],
    "path": "HatNFT::HatMinted"
},
        eventSelector: EventSelector.fromString("0x99f8ba0a"),
        fieldNames: ["token_id","owner","game_id","hat_type","hat_quality"],
      }
    };
  }
  
}
